name: release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  Build:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        run: bash release.sh ${{ github.ref }}
      - name: release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          files: |
            dist/*.bobplugin
      - name: clean up
        run: rm -rf dist
      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: new release!
